Updated build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -22,7 +22,13 @@ jobs:
       run: /usr/bin/xcodebuild -version    
     - uses: actions/checkout@v2
     - name: Build and Test Proton
-      run: xcodebuild build test -destination "name=iPhone 14 Pro" -scheme "Proton"
+      run: xcodebuild -resultBundlePath TestResults -scheme "Proton" -destination 'platform=iOS Simulator,name=iPhone 14 Pro,OS=16.4' clean test
+	- uses: kishikawakatsumi/xcresulttool@v1
+	  with:
+		  path: TestResults.xcresult
+	  if: success() || failure()
+	  # ^ This is important because the action will be run
+	  # even if the test fails in the previous step.
     - name: Build and Test Proton as dependency in another package
       run: xcodebuild build -destination "name=iPhone 14 Pro" -scheme "TestBuildPackage"
     - name: Capture Proton Code Coverage
